#!/bin/bash

camera_make='Nikon Corp.' # as seen in lsusb
outpath="./thumbs"
shrink=10

if [ $# -eq 0 ]; then
  frames=10
else
  frames=$1
fi

# reset the usb device
lsusb | grep "$camera_make" | awk '{print "/dev/bus/usb/",$2,"/",$4}' | sed 's/[: ]//g' | xargs -I {} ./usbreset {}

echo "Taking photos..."
gphoto2 --auto-detect --interval=1 --frames=$frames --capture-image-and-download --filename "20%y-%m-%d_%H:%M:%S.%C"

# detect format
format=`ls -ltp | grep -v / | grep -v total | head -n1 | grep -Eo "(JPG|NEF)"`
echo "Detected format: $format"

# make thumbnails
echo "Making thumbnails..."
if [ "$format" == "NEF" ]; then
    find . -name "*.$format" -print | sort -r | head -n $frames | xargs ufraw-batch --shrink=$shrink --out-type=jpg --out-path=$outpath --overwrite
elif [ "$format" == "JPG" ]; then
    # let's just use PIL
    find . -name "*.$format" -print | sort -r | sed 's/.\///' | head -n $frames | xargs -I {} ./resize.py -o $outpath -s $shrink {}

    # let's make sure we kill all those uppercase JPGs
    pushd $outpath
    for FILE in *.JPG; do mv $FILE ${FILE%.JPG}.jpg; done
    popd
fi

echo "Generating index page..."
# generate the index page
pushd $outpath
../make_index > index.html
popd



